# Generated by Django 6.0.2 on 2026-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country_user_date_of_birth_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_all_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_this_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
