# Generated by Django 6.0.2 on 2026-03-03 14:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_referral_codes(apps, schema_editor):
    """Give every existing user a unique referral code."""
    User = apps.get_model('accounts', 'User')
    used = set()
    for user in User.objects.filter(referral_code=''):
        code = uuid.uuid4().hex[:8].upper()
        while code in used or User.objects.filter(referral_code=code).exists():
            code = uuid.uuid4().hex[:8].upper()
        user.referral_code = code
        user.save(update_fields=['referral_code'])
        used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_balance_user_referral_bonus_and_more'),
    ]

    operations = [
        # Add referral_code as nullable first so existing rows aren't blocked
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, default=''),
            preserve_default=False,
        ),
        # Back-fill unique codes for existing users
        migrations.RunPython(assign_referral_codes, migrations.RunPython.noop),
        # Now enforce the unique constraint
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referrals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
