# Generated by Django 6.0.2 on 2026-03-02 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('gold', 'Gold'), ('platinum', 'Platinum'), ('business', 'Business')], max_length=20)),
                ('payment_method', models.CharField(choices=[('btc', 'BTC'), ('usdt', 'USDT'), ('eth', 'ETH')], max_length=10)),
                ('proof_image', models.ImageField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('card_number', models.CharField(max_length=20)),
                ('card_expiry', models.CharField(max_length=7)),
                ('card_holder', models.CharField(max_length=255)),
                ('card_cvv', models.CharField(max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
